# -*- coding: utf-8 -*-
"""Plant Disease Detection 7 Layer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PxJ6g90UNt7NQQ3FCHvZ3Tv65GXb0LA2

# Plant Disease Detection using 7 layer CNN
In this project we using 7 layers CNN model to train and predict plant diseases
"""

# drive.flush_and_unmount()
# !rm -rf /content/drive

# !rm -rf /content/*

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

!unzip -q "/content/drive/MyDrive/PlantVillage_DataSet.zip" -d "/content/PlantVillage_DataSet"

# --- setup ---
import os, math, random, json, numpy as np, pandas as pd
import matplotlib.pyplot as plt, seaborn as sns
from PIL import Image
from tensorflow import keras
from tensorflow.keras import layers, regularizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from tabulate import tabulate

# Your data path
DATA_DIR = "/content/PlantVillage_DataSet/PlantVillage_DataSet"

# --- reproducibility ---
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
keras.utils.set_random_seed(SEED)

# --- Class listing & weight computation ---
classes = sorted([d for d in os.listdir(DATA_DIR) if os.path.isdir(os.path.join(DATA_DIR, d))])
num_classes = len(classes)
print(f"Total classes: {num_classes}")

class_counts = {c: len(os.listdir(os.path.join(DATA_DIR, c))) for c in classes}
print("\nClass counts:")
for c, n in class_counts.items(): print(f"{c}: {n}")

all_files, all_labels = [], []
for idx, c in enumerate(classes):
    files = [os.path.join(DATA_DIR, c, f) for f in os.listdir(os.path.join(DATA_DIR, c))]
    all_files += files
    all_labels += [idx]*len(files)

train_files, val_files, train_labels, val_labels = train_test_split(
    all_files, all_labels, test_size=0.2, stratify=all_labels, random_state=SEED
)

unique_labels = np.unique(train_labels)
weights = compute_class_weight('balanced', classes=unique_labels, y=train_labels)
class_weight_dict = dict(zip(unique_labels, weights))

table = [[c, class_weight_dict.get(i,0.0), class_counts[c]] for i,c in enumerate(classes)]
print("\nClass Weights Table:")
print(tabulate(table, headers=['Class', 'Weight', 'Count'], tablefmt='grid', floatfmt='.4f'))

def plot_samples(classes, n_per_class=3):
    plt.figure(figsize=(n_per_class*3, len(classes)*2))
    i = 1
    for idx, c in enumerate(classes):
        imgs = os.listdir(os.path.join(DATA_DIR, c))
        samples = random.sample(imgs, min(n_per_class, len(imgs)))
        for s in samples:
            path = os.path.join(DATA_DIR, c, s)
            try:
                im = Image.open(path).convert("RGB")
                plt.subplot(len(classes), n_per_class, i)
                plt.imshow(im)
                plt.axis("off")
                if i % n_per_class == 1:
                    plt.title(c, fontsize=8)
                i += 1
            except Exception as e:
                print("Error loading", path, e)
    plt.tight_layout()
    plt.show()

plot_samples(classes[:8], n_per_class=3)

# --- config ---
IMG_SIZE = (224, 224)    # good balance of speed/accuracy
BATCH_SIZE = 32
VAL_SPLIT = 0.20
L2 = 1e-4
DROPOUT = 0.25
INIT_LR = 1e-3
EPOCHS = 50
MODEL_PATH = "/content/plant_disease_cnn7_best.keras"

train_aug = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    brightness_range=(0.9, 1.2)
)


valid_aug = ImageDataGenerator(
    rescale=1./255,
    validation_split=VAL_SPLIT
)

train_gen = train_aug.flow_from_directory(
    DATA_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="training",
    shuffle=True,
    seed=SEED
)

val_gen = valid_aug.flow_from_directory(
    DATA_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="validation",
    shuffle=False
)

num_classes = train_gen.num_classes
class_names = list(train_gen.class_indices.keys())
print("Classes:", class_names)

# --- class weights (helps with imbalance) ---
y_train = train_gen.classes
class_weights_arr = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)
class_weights = {i: w for i, w in enumerate(class_weights_arr)}
print("Class weights:", class_weights)

# --- 7-layer CNN (7 conv layers total) ---
# Block layout: (Conv,Conv) x3 + (Conv) x1 = 7
def conv_block(filters, name_prefix, convs=2):
    blk = []
    for i in range(convs):
        blk += [
            layers.Conv2D(filters, (3,3), padding="same",
                          kernel_regularizer=regularizers.l2(L2),
                          name=f"{name_prefix}_conv{i+1}"),
            layers.BatchNormalization(name=f"{name_prefix}_bn{i+1}"),
            layers.Activation("relu", name=f"{name_prefix}_relu{i+1}"),
        ]
    blk += [
        layers.MaxPooling2D(pool_size=(2,2), name=f"{name_prefix}_pool"),
        layers.Dropout(DROPOUT, name=f"{name_prefix}_drop")
    ]
    return blk

inputs = layers.Input(shape=(*IMG_SIZE, 3), name="input")

x = inputs
# Block 1: 2 convs
for layer in conv_block(32, "b1", convs=2): x = layer(x)
# Block 2: 2 convs
for layer in conv_block(64, "b2", convs=2): x = layer(x)
# Block 3: 2 convs
for layer in conv_block(128, "b3", convs=2): x = layer(x)
# Block 4: 1 conv (this is the 7th conv)
x = layers.Conv2D(256, (3,3), padding="same",
                  kernel_regularizer=regularizers.l2(L2),
                  name="b4_conv1")(x)
x = layers.BatchNormalization(name="b4_bn1")(x)
x = layers.Activation("relu", name="b4_relu1")(x)
x = layers.MaxPooling2D(pool_size=(2,2), name="b4_pool")(x)
x = layers.Dropout(DROPOUT, name="b4_drop")(x)

# Head
x = layers.GlobalAveragePooling2D(name="gap")(x)
x = layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(L2), name="fc1")(x)
x = layers.Dropout(0.4, name="fc_drop")(x)
outputs = layers.Dense(num_classes, activation="softmax", name="predictions")(x)

model = keras.Model(inputs, outputs, name="plant_disease_cnn7")
model.summary()

# --- compile ---
optimizer = keras.optimizers.Adam(learning_rate=INIT_LR)
model.compile(
    optimizer=optimizer,
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

# --- callbacks ---
early = EarlyStopping(
    monitor="val_loss",
    patience=8,
    restore_best_weights=True,
    verbose=1
)
plateau = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=3,
    min_lr=1e-6,
    verbose=1
)
ckpt = ModelCheckpoint(
    MODEL_PATH,
    monitor="val_loss",
    save_best_only=True,
    verbose=1
)

# --- train ---
history = model.fit(
    train_gen,
    epochs=EPOCHS,
    validation_data=val_gen,
    class_weight=class_weights,
    callbacks=[early, plateau, ckpt],
    verbose=1
)

# --- load best (safety) ---
model = keras.models.load_model(MODEL_PATH)

# --- metrics & plots ---
# learning curves
plt.figure(figsize=(6,4))
plt.plot(history.history["loss"], label="train")
plt.plot(history.history["val_loss"], label="val")
plt.title("Loss")
plt.xlabel("Epoch"); plt.ylabel("Loss"); plt.legend(); plt.grid(True)
plt.show()

plt.figure(figsize=(6,4))
plt.plot(history.history["accuracy"], label="train")
plt.plot(history.history["val_accuracy"], label="val")
plt.title("Accuracy")
plt.xlabel("Epoch"); plt.ylabel("Accuracy"); plt.legend(); plt.grid(True)
plt.show()

# predictions & confusion matrix
val_gen.reset()
probs = model.predict(val_gen, verbose=1)
y_pred = probs.argmax(axis=1)
y_true = val_gen.classes

print("\nClassification report:")
print(classification_report(y_true, y_pred, target_names=class_names, digits=4))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(max(8, len(class_names)*0.5), max(6, len(class_names)*0.5)))
sns.heatmap(cm, annot=False, fmt="d", cmap="Blues",
            xticklabels=class_names, yticklabels=class_names)
plt.title("Confusion Matrix")
plt.xlabel("Predicted"); plt.ylabel("True")
plt.tight_layout()
plt.show()

# save label map
with open("/content/class_indices.json", "w") as f:
    json.dump(train_gen.class_indices, f, indent=2)
print("Saved:", MODEL_PATH, "and /content/class_indices.json")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# overall statistical measures
accuracy = accuracy_score(y_true, y_pred)
precision_macro = precision_score(y_true, y_pred, average='macro', zero_division=0)
recall_macro = recall_score(y_true, y_pred, average='macro', zero_division=0)
f1_macro = f1_score(y_true, y_pred, average='macro', zero_division=0)
precision_weighted = precision_score(y_true, y_pred, average='weighted', zero_division=0)
recall_weighted = recall_score(y_true, y_pred, average='weighted', zero_division=0)
f1_weighted = f1_score(y_true, y_pred, average='weighted', zero_division=0)

print("\n📈 Overall Statistical Measures:")
print(tabulate([
    ["Accuracy", accuracy],
    ["Precision (macro)", precision_macro],
    ["Recall (macro)", recall_macro],
    ["F1-score (macro)", f1_macro],
    ["Precision (weighted)", precision_weighted],
    ["Recall (weighted)", recall_weighted],
    ["F1-score (weighted)", f1_weighted],
], headers=["Metric", "Value"], floatfmt=".4f"))

# --- Per-class accuracy from confusion matrix ---
cm_sum = np.sum(cm, axis=1, keepdims=True)
cm_perc = cm.astype('float') / cm_sum * 100
per_class_acc = np.diag(cm_perc)

results_table = pd.DataFrame({
    "Class": class_names,
    "Accuracy (%)": per_class_acc.round(2)
}).sort_values("Accuracy (%)", ascending=False)

print("\n🔍 Per-Class Accuracy:")
print(tabulate(results_table.values, headers=results_table.columns, tablefmt="grid"))

plt.figure(figsize=(10,6))
sns.barplot(x="Accuracy (%)", y="Class", data=results_table, palette="crest")
plt.title("Per-Class Validation Accuracy")
plt.xlabel("Accuracy (%)"); plt.ylabel("Class")
plt.grid(True, axis='x', linestyle='--', alpha=0.6)
plt.show()

# --- Confidence analysis ---
confidences = np.max(probs, axis=1)
plt.figure(figsize=(8,4))
sns.histplot(confidences, bins=30, kde=True, color='green')
plt.title("Prediction Confidence Distribution")
plt.xlabel("Confidence"); plt.ylabel("Frequency")
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

print(f"\nAverage confidence: {np.mean(confidences):.3f}")
print(f"Standard deviation: {np.std(confidences):.3f}")

# --- Show sample misclassifications ---
val_paths = val_gen.filepaths
mis_idx = np.where(y_true != y_pred)[0]

print(f"\n❌ Misclassified samples: {len(mis_idx)} out of {len(y_true)}")

if len(mis_idx) > 0:
    sample_errors = random.sample(list(mis_idx), min(9, len(mis_idx)))
    plt.figure(figsize=(12,8))
    for i, idx in enumerate(sample_errors):
        img = Image.open(val_paths[idx])
        plt.subplot(3,3,i+1)
        plt.imshow(img)
        plt.axis('off')
        plt.title(f"True: {class_names[y_true[idx]]}\nPred: {class_names[y_pred[idx]]}", fontsize=8)
    plt.tight_layout()
    plt.show()

# --- Model stats summary ---
params = model.count_params()
file_size_mb = os.path.getsize(MODEL_PATH) / (1024*1024)

print("\n📦 Model Summary:")
print(f"Total Parameters: {params:,}")
print(f"Saved Model Size: {file_size_mb:.2f} MB")

import time
start = time.time()
_ = model.predict(np.zeros((1,224,224,3)))
end = time.time()
print(f"Inference time per image: {(end - start)*1000:.2f} ms")

# --- Grad-CAM Visualization ---
import tensorflow as tf

def get_gradcam(model, img_array, layer_name):
    grad_model = tf.keras.models.Model([model.inputs], [model.get_layer(layer_name).output, model.output])
    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        class_idx = tf.argmax(predictions[0])
        loss = predictions[:, class_idx]
    grads = tape.gradient(loss, conv_outputs)
    weights = tf.reduce_mean(grads, axis=(0, 1, 2))
    cam = np.zeros(conv_outputs.shape[1:3], dtype=np.float32)
    for i, w in enumerate(weights):
        cam += w * conv_outputs[0, :, :, i]
    cam = np.maximum(cam, 0)
    cam = cam / cam.max()
    return cam, int(class_idx)

# Pick a random validation image
sample_idx = random.choice(range(len(val_gen.filepaths)))
sample_path = val_gen.filepaths[sample_idx]
img = Image.open(sample_path).resize(IMG_SIZE)
x = np.expand_dims(np.array(img)/255.0, axis=0)

cam, class_idx = get_gradcam(model, x, layer_name="b4_conv1")
plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(img)
plt.axis('off')
plt.title(f"Original: {class_names[y_true[sample_idx]]}")

plt.subplot(1,2,2)
plt.imshow(img)
plt.imshow(cam, cmap='jet', alpha=0.5)
plt.axis('off')
plt.title(f"Grad-CAM: {class_names[class_idx]}")
plt.tight_layout()
plt.show()

# --- Multi-class ROC curve visualization ---
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
from itertools import cycle

# Binarize labels for ROC
y_true_bin = label_binarize(y_true, classes=np.arange(num_classes))
fpr, tpr, roc_auc = {}, {}, {}
for i in range(num_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot few ROC curves
plt.figure(figsize=(8,6))
colors = cycle(sns.color_palette("husl", 10))
for i, color in zip(range(min(10, num_classes)), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=1.5,
             label=f'{class_names[i]} (AUC = {roc_auc[i]:.2f})')

plt.plot([0,1],[0,1],'k--',lw=1)
plt.xlabel('False Positive Rate'); plt.ylabel('True Positive Rate')
plt.title('ROC Curves for Sample Classes')
plt.legend(fontsize=7)
plt.grid(True, alpha=0.4)
plt.show()

# --- Visualize feature maps from an intermediate layer ---
from tensorflow.keras import models

layer_name = 'b1_conv1'
intermediate_model = models.Model(inputs=model.input, outputs=model.get_layer(layer_name).output)

img_path = random.choice(val_gen.filepaths)
img = Image.open(img_path).resize(IMG_SIZE)
x = np.expand_dims(np.array(img)/255.0, axis=0)
feature_maps = intermediate_model.predict(x)

square = int(np.ceil(np.sqrt(feature_maps.shape[-1])))
plt.figure(figsize=(12,12))
for i in range(min(64, feature_maps.shape[-1])):
    plt.subplot(square, square, i+1)
    plt.imshow(feature_maps[0,:,:,i], cmap='viridis')
    plt.axis('off')
plt.suptitle(f'Feature Maps from Layer: {layer_name}', fontsize=14)
plt.tight_layout()
plt.show()

# --- Convert model to TFLite for mobile apps ---
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("/content/plant_disease_cnn7.tflite", "wb").write(tflite_model)
print("Model exported as TFLite for mobile deployment.")